server {
    listen 80;
    listen [::]:80;
    server_name jinchen-ai.com www.jinchen-ai.com;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name jinchen-ai.com www.jinchen-ai.com;

    root /var/www/jinchen-ai.com;
    access_log /var/log/nginx/jinchen-ai.com.access.log;
    error_log /var/log/nginx/jinchen-ai.com.error.log;

    ssl_certificate /etc/nginx/ssl/jinchen-ai.com/fullchain.crt;
    ssl_certificate_key /etc/nginx/ssl/jinchen-ai.com/privkey.key;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    location = / {
        return 302 /words/;
    }

    location = /words {
        return 301 /words/;
    }

    location /words/ {
        alias /var/www/jinchen-ai.com/words/current/;
        index index.html;
        try_files $uri $uri/ /words/index.html;
    }
}
